Feature/us08
robertschaedler3/SSW-555 pull request #20
Opened 2020-09-25 16:17 UTC by robertschaedler3

Added check for birth after marriage of a parent.

#12

2020-09-26 20:15 UTC, aej11a approved these changes

2020-09-26 20:17 UTC, aej11a requested changes
You probably need to update this after merging https://github.com/robertschaedler3/SSW-555/pull/21 because I renamed the children and spouse family properties to be more consistent with GEDCOM tags and reduce confusion

2020-09-28 04:11 UTC, Liam-Brew approved these changes
Looks good

2020-09-28 06:52 UTC, allen-best approved these changes
Looks good.

2020-09-28 16:41 UTC, merged