US24
robertschaedler3/SSW-555 pull request #92
Opened 2020-10-26 16:14 UTC by conniexu444

2020-10-26 16:16 UTC, robertschaedler3 requested changes
Can you add test cases for this story as well?

2020-10-26 16:17 UTC, conniexu444 commented
Can you respond to my texts? The answer to both quesstions is Nope 🙂
________________________________
From: Robert Schaedler III <notifications@github.com>
Sent: Monday, October 26, 2020 9:16 AM
To: robertschaedler3/SSW-555 <SSW-555@noreply.github.com>
Cc: Constance G Xu <cxu16@stevens.edu>; Author <author@noreply.github.com>
Subject: Re: [robertschaedler3/SSW-555] US24 (#92)


@robertschaedler3 requested changes on this pull request.

Can you add test cases for this story as well?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frobertschaedler3%2FSSW-555%2Fpull%2F92%23pullrequestreview-516945789&data=04%7C01%7Ccxu16%40stevens.edu%7C4ec8ff98c3dd41e4055c08d879ca88d3%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637393258071607803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8BbaHX%2FjNiA0SONGPUJsOJdbNOmpAofEdzAIPa32Pis%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKJZGHE6J2KYU7VMJLCMVMDSMWOG3ANCNFSM4S7S7LAA&data=04%7C01%7Ccxu16%40stevens.edu%7C4ec8ff98c3dd41e4055c08d879ca88d3%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637393258071607803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=o2bbGVcr7SewXAtOAj8AZ6C%2FQtyIVIsGVqI6Qzdm9vk%3D&reserved=0>.

2020-10-26 16:44 UTC, robertschaedler3 approved these changes

2020-10-26 17:03 UTC, robertschaedler3 commented
Added unit tests to resolve above.

2020-10-26 21:44 UTC, aej11a commented on src/main/java/gedcom/validators/UniqueFamiliesBySpouses.java
> +                    System.out.println("Anomaly US24: No more than one family with the same spouses by name and the same marriage date should appear in GEDCOM file");
Can you please add the Family ID in this message somewhere? It would be nice to give the problematic individual too but not needed

2020-10-27 01:21 UTC, robertschaedler3 commented on src/main/java/gedcom/validators/UniqueFamiliesBySpouses.java
> +                    System.out.println("Anomaly US24: No more than one family with the same spouses by name and the same marriage date should appear in GEDCOM file");
Added families to output. Further context (problematic individuals) will be added by resolving #58 in a separate PR soon.

2020-10-27 01:36 UTC, Liam-Brew approved these changes

2020-10-27 01:42 UTC, merged